server:
  port: ${PORT:8090}
spring:
  application:
    name: ocr
endpoints:
  actuator:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true

google:
  api:
    key: ${GOOGLE_API_KEY}
